const http = require('node:http');
const { readFile, stat } = require('node:fs/promises');
const { existsSync, readFileSync } = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const ROOT = path.resolve(__dirname, '..');
const PUBLIC_ROOT = path.join(ROOT, 'public');
function loadEnv(file=path.join(ROOT,'.env')) { if(!existsSync(file)) return; for(const line of readFileSync(file,'utf8').split(/\r?\n/)){const entry=line.trim();if(!entry||entry.startsWith('#'))continue;const i=entry.indexOf('=');if(i<1)continue;const key=entry.slice(0,i).trim(),value=entry.slice(i+1).trim().replace(/^(['"])(.*)\1$/,'$2');if(process.env[key]===undefined)process.env[key]=value} }
loadEnv();
const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const NODE_ENV = process.env.NODE_ENV || 'development';
const DB_FILE = path.resolve(ROOT, process.env.DB_FILE || 'compras-control.db');
const SESSION_TTL_MS = Math.max(1, Number(process.env.SESSION_TTL_HOURS || 8)) * 60 * 60 * 1000;
const MAX_BODY_BYTES = Math.max(1_000, Number(process.env.MAX_BODY_BYTES || 3_200_000));
const COOKIE_SECURE = String(process.env.COOKIE_SECURE || 'auto').toLowerCase();
const TRUST_PROXY = process.env.TRUST_PROXY === 'true';
const db = new DatabaseSync(DB_FILE);
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('Administrador','Comprador','Consulta')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS suppliers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, cnpj TEXT, contact TEXT, phone TEXT, email TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, cnpj TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY, name TEXT NOT NULL, code TEXT, category TEXT, unit TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS invoices (id INTEGER PRIMARY KEY, number TEXT NOT NULL, date TEXT NOT NULL, supplier TEXT NOT NULL, sector TEXT NOT NULL, total REAL NOT NULL CHECK(total >= 0), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
db.exec('PRAGMA journal_mode = WAL; PRAGMA busy_timeout = 5000;');
db.exec('CREATE TABLE IF NOT EXISTS plans (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');
db.exec('CREATE INDEX IF NOT EXISTS idx_products_name ON products(name); CREATE INDEX IF NOT EXISTS idx_products_code ON products(code);');
try { db.exec("ALTER TABLE invoices ADD COLUMN plan_code TEXT NOT NULL DEFAULT ''"); } catch { /* coluna já existe */ }
for (const column of ["purchase_location TEXT NOT NULL DEFAULT ''", "company TEXT NOT NULL DEFAULT ''", "expense_type TEXT NOT NULL DEFAULT ''", "product_name TEXT NOT NULL DEFAULT ''", "quantity REAL NOT NULL DEFAULT 0"]) { try { db.exec(`ALTER TABLE invoices ADD COLUMN ${column}`); } catch { /* coluna já existe */ } }
db.prepare("DELETE FROM plans WHERE code='ADM' AND name='Administrativo' AND NOT EXISTS (SELECT 1 FROM invoices WHERE plan_code='ADM')").run();
for (const [code, name] of [['ERIMAR','Erimar'],['LEITE','Leite'],['BLOCOS','Blocos'],['RANCHO','Rancho'],['MARK','Mark']]) {
  db.prepare('INSERT OR IGNORE INTO companies(code,name) VALUES(?,?)').run(code,name);
}

const scrypt = (password, salt) => crypto.scryptSync(password, salt, 64).toString('hex');
const hashPassword = password => { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${scrypt(password, salt)}`; };
const verifyPassword = (password, saved) => { const [salt, hash] = saved.split(':'); return crypto.timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(scrypt(password, salt), 'hex')); };
const ADMIN_EMAIL = String(process.env.ADMIN_EMAIL || 'admin@erimax.com').trim().toLowerCase();
const ADMIN_PASSWORD = String(process.env.ADMIN_PASSWORD || 'Erimax@2026');
if (!db.prepare('SELECT id FROM users WHERE email = ?').get(ADMIN_EMAIL)) db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES (?,?,?,?)').run('Administrador', ADMIN_EMAIL, hashPassword(ADMIN_PASSWORD), 'Administrador');
if (process.env.RESET_ADMIN_PASSWORD === 'true') db.prepare('UPDATE users SET password_hash=? WHERE email=?').run(hashPassword(ADMIN_PASSWORD), ADMIN_EMAIL);

const roles = { Administrador: 3, Comprador: 2, Consulta: 1 };
const cookie = (req, name) => (req.headers.cookie || '').split(';').map(x => x.trim()).find(x => x.startsWith(`${name}=`))?.slice(name.length + 1);
const sessionUser = req => { const token = cookie(req, 'cc_session'); if (!token) return null; const tokenHash = crypto.createHash('sha256').update(token).digest('hex'); return db.prepare('SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').get(tokenHash, Date.now()) || null; };
const securityHeaders = {'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; img-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"};
const send = (res, status, payload, headers = {}) => { res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...securityHeaders, ...headers}); res.end(JSON.stringify(payload)); };
const body = req => new Promise((resolve, reject) => { let raw='',size=0,done=false; req.on('data', c => {size+=c.length;if(size>MAX_BODY_BYTES){done=true;reject(new Error('A solicitação excede o tamanho permitido.'));req.destroy();return}if(!done)raw+=c});req.on('end', () => {if(done)return;try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('JSON inválido'))}});req.on('error', reject); });
const auth = (req, res, minimum = 1) => { const user = sessionUser(req); if (!user) { send(res, 401, {error:'Sessão inválida ou expirada.'}); return null; } if (roles[user.role] < minimum) { send(res, 403, {error:'Você não tem permissão para esta ação.'}); return null; } return user; };
const clean = x => String(x || '').trim();
const attempts = new Map();
const clientIp = req => TRUST_PROXY ? (req.headers['x-forwarded-for']||'').split(',')[0].trim() || req.socket.remoteAddress : req.socket.remoteAddress;
const cookieSecure = req => COOKIE_SECURE === 'true' || (COOKIE_SECURE !== 'false' && (req.socket.encrypted || (TRUST_PROXY && req.headers['x-forwarded-proto']==='https')));
const loginAllowed = req => { const now=Date.now(),ip=clientIp(req),item=attempts.get(ip);if(!item||now-item.started>900_000){attempts.set(ip,{started:now,count:1});return true}if(item.count>=10)return false;item.count++;return true };

function xmlValue(xml, tag) { const found = xml.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`, 'i')); return found ? found[1].replace(/<!\[CDATA\[|\]\]>/g, '').replace(/&amp;/g, '&').trim() : ''; }
function importNfe(xml) { if (typeof xml !== 'string' || xml.length > 3_000_000 || !/<(?:nfeProc:)?NFe[ >]/i.test(xml)) throw new Error('Envie um XML válido de NF-e.'); const number=xmlValue(xml,'nNF'), date=(xmlValue(xml,'dhEmi')||xmlValue(xml,'dEmi')).slice(0,10), supplier=xmlValue(xml,'xNome'), total=Number(xmlValue(xml,'vNF')); if(!number||!date||!supplier||!Number.isFinite(total)) throw new Error('Não foi possível localizar número, emissão, emitente e valor total no XML.'); return {number,date,supplier,total}; }
const norm = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const BOM_PATTERN = /^\ufeff/;
function csvRows(text) { const rows=[]; let row=[],value='',quoted=false; for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(!quoted&&(ch===';'||ch==='|'||ch===',')){row.push(value.trim());value=''}else if(!quoted&&(ch==='\n'||ch==='\r')){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(value.trim());if(row.some(Boolean))rows.push(row);row=[];value=''}else value+=ch}row.push(value.trim());if(row.some(Boolean))rows.push(row);return rows; }
function importCsv(text) { if(typeof text!=='string'||text.length>3_000_000)throw new Error('Envie um CSV de até 3 MB.'); const rows=csvRows(text.replace(/^\uFEFF/,''));if(rows.length<2)throw new Error('O CSV precisa ter cabeçalho e ao menos uma linha.');const header=rows.shift().map(norm),index=(...names)=>header.findIndex(h=>names.includes(h));const ix={date:index('data','datacompra'),location:index('localdecompra','local'),company:index('qualempresa','empresa'),sector:index('setor'),expense:index('tipodedespesa','despesa'),product:index('produto'),quantity:index('quantidade','qtd'),total:index('valortotal','valor')};if(Object.values(ix).some(x=>x<0))throw new Error('Use as colunas: DATA, LOCAL DE COMPRA, QUAL EMPRESA, SETOR, TIPO DE DESPESA, PRODUTO, QUANTIDADE e VALOR TOTAL.');return rows.map((r,n)=>{const get=k=>clean(r[ix[k]]),rawDate=get('date'),date=/^\d{2}\/\d{2}\/\d{4}$/.test(rawDate)?`${rawDate.slice(6)}-${rawDate.slice(3,5)}-${rawDate.slice(0,2)}`:rawDate;const company=get('company').toUpperCase(),total=Number(get('total').replace(/\./g,'').replace(',','.')),quantity=Number(get('quantity').replace(',','.'));if(!date||!get('location')||!company||!get('sector')||!get('expense')||!get('product')||!Number.isFinite(quantity)||!Number.isFinite(total))throw new Error(`Linha ${n+2}: confira todos os campos obrigatórios.`);return {date,location:get('location'),company,sector:get('sector'),expense:get('expense'),product:get('product'),quantity,total};}); }
function importProductsCsv(text) { if(typeof text!=='string'||text.length>3_000_000)throw new Error('Envie um CSV de até 3 MB.'); const rows=csvRows(text.replace(BOM_PATTERN,''));if(rows.length<2)throw new Error('O CSV precisa ter cabeçalho e ao menos uma linha.');const header=rows.shift().map(norm),index=(...names)=>header.findIndex(h=>names.includes(h));const ix={name:index('produto','nome','nomedoproduto'),code:index('codigo','codigointerno'),category:index('categoria','tipodedespesa'),unit:index('unidade','un')};if(ix.name<0)throw new Error('Use o modelo de colunas disponibilizado (é necessária ao menos a coluna PRODUTO).');return rows.map((r,n)=>{const get=k=>ix[k]>=0?clean(r[ix[k]]):'',name=get('name');if(!name)throw new Error(`Linha ${n+2}: informe o nome do produto.`);return {name,code:get('code'),category:get('category'),unit:get('unit')||'UN'};}); }
async function api(req, res, url) {
  const method = req.method;
  if (method === 'GET' && url.pathname === '/health') return send(res,200,{ok:true});
  if (method === 'POST' && url.pathname === '/api/auth/login') { if(!loginAllowed(req)) return send(res,429,{error:'Muitas tentativas. Aguarde alguns minutos e tente novamente.'},{'Retry-After':'900'}); const {email, password} = await body(req); const user = db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(clean(email).toLowerCase()); if (!user || !verifyPassword(password || '', user.password_hash)) return send(res, 401, {error:'E-mail ou senha incorretos.'}); attempts.delete(clientIp(req)); const token = crypto.randomBytes(32).toString('base64url'); const tokenHash = crypto.createHash('sha256').update(token).digest('hex'); db.prepare('DELETE FROM sessions WHERE expires_at <= ?').run(Date.now()); db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES (?,?,?)').run(tokenHash,user.id,Date.now()+SESSION_TTL_MS); return send(res,200,{user:{id:user.id,name:user.name,email:user.email,role:user.role}},{'Set-Cookie':`cc_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${Math.floor(SESSION_TTL_MS/1000)}${cookieSecure(req)?'; Secure':''}`}); }
  if (method === 'POST' && url.pathname === '/api/auth/logout') { const token=cookie(req,'cc_session'); if(token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(crypto.createHash('sha256').update(token).digest('hex')); return send(res,200,{ok:true},{'Set-Cookie':'cc_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'}); }
  if (method === 'GET' && url.pathname === '/api/auth/me') { const user=auth(req,res); if(user) send(res,200,{user}); return; }
  const user=auth(req,res); if (!user) return;
  if (method === 'POST' && url.pathname === '/api/invoices/import-csv') { if(roles[user.role]<2)return send(res,403,{error:'Você não tem permissão para importar compras.'}); try { const entries=importCsv((await body(req)).csv); db.exec('BEGIN'); try { for(const x of entries){let sector=db.prepare('SELECT code FROM plans WHERE code=? OR name=?').get(x.sector.toUpperCase(),x.sector);if(!sector){const code=x.sector.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,20)||'SETOR';let unique=code,n=2;while(db.prepare('SELECT id FROM plans WHERE code=?').get(unique))unique=`${code.slice(0,17)}${n++}`;db.prepare('INSERT INTO plans(code,name) VALUES(?,?)').run(unique,x.sector);sector={code:unique}}if(!db.prepare('SELECT id FROM companies WHERE code=?').get(x.company))db.prepare('INSERT INTO companies(code,name) VALUES(?,?)').run(x.company,x.company);if(!db.prepare('SELECT id FROM categories WHERE name=?').get(x.expense))db.prepare('INSERT INTO categories(name) VALUES(?)').run(x.expense);if(!db.prepare('SELECT id FROM suppliers WHERE name=?').get(x.location))db.prepare('INSERT INTO suppliers(name) VALUES(?)').run(x.location);(()=>{const existingProduct=db.prepare('SELECT id FROM products WHERE name=?').get(x.product);if(existingProduct)db.prepare('UPDATE products SET category=?,unit=? WHERE id=?').run(x.expense,'UN',existingProduct.id);else db.prepare('INSERT INTO products(name,code,category,unit) VALUES(?,?,?,?)').run(x.product,'',x.expense,'UN')})();db.prepare('INSERT INTO invoices(number,date,supplier,sector,plan_code,total,purchase_location,company,expense_type,product_name,quantity) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(`CSV-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,x.date,x.location,sector.code,sector.code,x.total,x.location,x.company,x.expense,x.product,x.quantity)} db.exec('COMMIT');return send(res,201,{imported:entries.length});}catch(e){db.exec('ROLLBACK');throw e}}catch(e){return send(res,400,{error:e.message||'Não foi possível importar o CSV.'})} }
  if (method === 'POST' && url.pathname === '/api/invoices/import-xml') { if(roles[user.role]<2) return send(res,403,{error:'Você não tem permissão para importar notas.'}); try { const parsed=importNfe((await body(req)).xml); const exists=db.prepare('SELECT id FROM invoices WHERE number=? AND supplier=?').get(parsed.number,parsed.supplier); if(exists) return send(res,409,{error:'Esta nota já foi importada.'}); if(!db.prepare('SELECT id FROM suppliers WHERE name=?').get(parsed.supplier)) db.prepare('INSERT INTO suppliers(name) VALUES(?)').run(parsed.supplier); const r=db.prepare('INSERT INTO invoices(number,date,supplier,sector,plan_code,total) VALUES(?,?,?,?,?,?)').run(parsed.number,parsed.date,parsed.supplier,'','',parsed.total); return send(res,201,{id:r.lastInsertRowid,invoice:parsed}); } catch(e) { return send(res,400,{error:e.message||'Não foi possível importar o XML.'}); } }
  if (method === 'POST' && url.pathname === '/api/products/import-csv') { if(roles[user.role]<2) return send(res,403,{error:'Sem permissão.'}); try { const entries=importProductsCsv((await body(req)).csv); let imported=0,updated=0; db.exec('BEGIN'); try { for(const x of entries){const existing=db.prepare('SELECT id FROM products WHERE name=?').get(x.name);if(existing){db.prepare('UPDATE products SET code=?,category=?,unit=? WHERE id=?').run(x.code,x.category,x.unit,existing.id);updated++}else{db.prepare('INSERT INTO products(name,code,category,unit) VALUES(?,?,?,?)').run(x.name,x.code,x.category,x.unit);imported++}} db.exec('COMMIT');return send(res,201,{imported,updated});}catch(e){db.exec('ROLLBACK');throw e}}catch(e){return send(res,400,{error:e.message||'Não foi possível importar o CSV.'})} }
  const entityMatch = url.pathname.match(/^\/api\/(suppliers|products|invoices|users|plans|companies|categories)(?:\/(\d+))?$/);
  const entity = entityMatch?.[1], entityId = Number(entityMatch?.[2] || 0);
  if (method === 'GET' && entity === 'plans') return send(res,200,{items:db.prepare('SELECT * FROM plans WHERE active=1 ORDER BY code').all()});
  if (method === 'POST' && entity === 'plans') { if(roles[user.role]<2) return send(res,403,{error:'Sem permissão para criar planos.'}); const v=await body(req),code=clean(v.code).toUpperCase(),name=clean(v.name); if(!/^[A-Z0-9._-]{2,20}$/.test(code)||!name)return send(res,400,{error:'Informe um código (2 a 20 caracteres) e um nome.'}); try {const r=db.prepare('INSERT INTO plans(code,name) VALUES(?,?)').run(code,name);return send(res,201,{id:r.lastInsertRowid})}catch{return send(res,409,{error:'Este código já está cadastrado.'})} }
  if (method === 'POST' && entity === 'invoices') { if(roles[user.role]<2)return send(res,403,{error:'Sem permissão para lançar notas.'}); const v=await body(req),number=clean(v.number),date=clean(v.date),supplier=clean(v.supplier),planCode=clean(v.planCode),company=clean(v.company).toUpperCase(),expense=clean(v.expenseType),product=clean(v.productName),quantity=Number(v.quantity),total=Number(v.total); if(!number||!date||!supplier||!planCode||!db.prepare('SELECT id FROM plans WHERE code=?').get(planCode)||!Number.isFinite(total)||total<0)return send(res,400,{error:'Preencha os dados obrigatórios da compra.'}); const r=db.prepare('INSERT INTO invoices(number,date,supplier,sector,plan_code,total,purchase_location,company,expense_type,product_name,quantity) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(number,date,supplier,planCode,planCode,total,supplier,company,expense,product,Number.isFinite(quantity)?quantity:0);return send(res,201,{id:r.lastInsertRowid}); }
  if (method === 'PATCH' && entity === 'users' && entityId) { if(roles[user.role]<3) return send(res,403,{error:'Apenas administradores podem editar usuários.'}); const v=await body(req),name=clean(v.name),email=clean(v.email).toLowerCase(),role=clean(v.role),active=clean(v.active)!=='false'; if(!name||!/^\S+@\S+\.\S+$/.test(email)||!roles[role]) return send(res,400,{error:'Informe os dados obrigatórios.'}); const password=String(v.password||''); if(password&&password.length<8) return send(res,400,{error:'A senha deve ter ao menos 8 caracteres.'}); try { if(password) db.prepare('UPDATE users SET name=?,email=?,role=?,active=?,password_hash=? WHERE id=?').run(name,email,role,active?1:0,hashPassword(password),entityId); else db.prepare('UPDATE users SET name=?,email=?,role=?,active=? WHERE id=?').run(name,email,role,active?1:0,entityId); return send(res,200,{ok:true}); } catch { return send(res,409,{error:'Este e-mail já está cadastrado.'}); } }
  if (method === 'DELETE' && entity === 'users' && entityId) { if(roles[user.role]<3) return send(res,403,{error:'Apenas administradores podem excluir usuários.'}); if(entityId===user.id) return send(res,400,{error:'Você não pode excluir seu próprio usuário.'}); db.prepare('DELETE FROM users WHERE id=?').run(entityId); return send(res,200,{ok:true}); }
  if (method === 'PATCH' && entity && entityId) { if(roles[user.role]<2)return send(res,403,{error:'Você não tem permissão para editar este cadastro.'}); const v=await body(req); let fields=[]; if(entity==='suppliers') fields=['name','cnpj','contact','phone','email']; else if(entity==='products') fields=['name','code','category','unit']; else if(entity==='plans') fields=['code','name']; else if(entity==='companies') fields=['code','name','cnpj']; else if(entity==='categories') fields=['name','description']; else if(entity==='invoices') fields=['number','date','supplier','sector','plan_code','total','purchase_location','company','expense_type','product_name','quantity']; else return send(res,405,{error:'Este registro não pode ser editado.'}); const values=fields.map(f=>f==='total'||f==='quantity'?Number(v[f]||0):clean(v[f])); if(entity==='plans'||entity==='companies')values[0]=values[0].toUpperCase(); if(entity==='invoices'){const planCode=clean(v.planCode||v.plan_code); if(!db.prepare('SELECT id FROM plans WHERE code=?').get(planCode))return send(res,400,{error:'Selecione um setor válido.'}); values[3]=planCode;values[4]=planCode;values[6]=values[2];} try { const r=db.prepare(`UPDATE ${entity} SET ${fields.map(f=>`${f}=?`).join(',')} WHERE id=?`).run(...values,entityId); if(!r.changes)return send(res,404,{error:'Registro não encontrado.'}); return send(res,200,{ok:true}); } catch { return send(res,409,{error:'Não foi possível salvar: verifique dados duplicados.'}); } }
  if (method === 'GET' && entity === 'products') { const page=Math.max(1,Number(url.searchParams.get('page'))||1),limit=Math.min(100,Math.max(10,Number(url.searchParams.get('limit'))||50)),q=clean(url.searchParams.get('q')); const where=q?'WHERE name LIKE ? COLLATE NOCASE OR code LIKE ? COLLATE NOCASE OR category LIKE ? COLLATE NOCASE':''; const params=q?[`%${q}%`,`%${q}%`,`%${q}%`]:[]; const total=db.prepare(`SELECT COUNT(*) AS total FROM products ${where}`).get(...params).total; const items=db.prepare(`SELECT * FROM products ${where} ORDER BY name COLLATE NOCASE, id LIMIT ? OFFSET ?`).all(...params,limit,(page-1)*limit); return send(res,200,{items,total,page,limit,pages:Math.max(1,Math.ceil(total/limit))}); }
  if (method === 'GET' && entity) { if(entity==='users' && roles[user.role]<3) return send(res,403,{error:'Apenas administradores podem consultar usuários.'}); const rows=db.prepare(`SELECT ${entity==='users'?'id,name,email,role,active,created_at':'*'} FROM ${entity} ORDER BY id DESC`).all(); return send(res,200,{items:rows}); }
  if (method === 'POST' && entity) { const min=entity==='users'?3:2; if(roles[user.role]<min) return send(res,403,{error:'Você não tem permissão para este cadastro.'}); const v=await body(req); if(entity==='users') { const name=clean(v.name), email=clean(v.email).toLowerCase(), role=clean(v.role), password=String(v.password||''); if(!name || !/^\S+@\S+\.\S+$/.test(email) || !roles[role] || password.length<8) return send(res,400,{error:'Informe nome, e-mail válido, perfil e uma senha de ao menos 8 caracteres.'}); try { const r=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES (?,?,?,?)').run(name,email,hashPassword(password),role); return send(res,201,{id:r.lastInsertRowid}); } catch { return send(res,409,{error:'Este e-mail já está cadastrado.'}); } }
    if(entity==='invoices') { const number=clean(v.number),date=clean(v.date),supplier=clean(v.supplier),sector=clean(v.sector),total=Number(v.total); if(!number||!date||!supplier||!sector||!Number.isFinite(total)||total<0) return send(res,400,{error:'Preencha todos os campos da nota fiscal.'}); const r=db.prepare('INSERT INTO invoices(number,date,supplier,sector,total) VALUES(?,?,?,?,?)').run(number,date,supplier,sector,total); return send(res,201,{id:r.lastInsertRowid}); }
    const name=clean(v.name); if(!name) return send(res,400,{error:'O nome é obrigatório.'}); const fields=entity==='suppliers'?['name','cnpj','contact','phone','email']:entity==='products'?['name','code','category','unit']:entity==='companies'?['code','name','cnpj']:['name','description']; const values=fields.map(k=>clean(v[k])); if(entity==='companies'&&!/^[A-Z0-9._-]{2,20}$/.test(values[0].toUpperCase()))return send(res,400,{error:'Informe um código de empresa entre 2 e 20 caracteres.'}); try { const r=db.prepare(`INSERT INTO ${entity}(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).run(...values); return send(res,201,{id:r.lastInsertRowid}); } catch { return send(res,409,{error:'Já existe um cadastro com esses dados.'}); } }
  return send(res,404,{error:'Recurso não encontrado.'});
}
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.ico':'image/x-icon'};
async function staticFile(req,res,url) { let file=url.pathname === '/' ? 'app.html' : url.pathname === '/login' ? 'login.html' : url.pathname.replace(/^\//,''); if (!['app.html','login.html'].includes(file) && !file.startsWith('assets/') && !['styles.css','login.css','app.js','login.js'].includes(file)) { res.writeHead(404,securityHeaders); return res.end('Não encontrado'); } try { const full=path.join(PUBLIC_ROOT,file); if(!full.startsWith(PUBLIC_ROOT) || !(await stat(full)).isFile()) throw new Error(); const content=await readFile(full),isAsset=file.startsWith('assets/'); res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':isAsset?'public, max-age=86400':'no-cache',...securityHeaders});res.end(content); } catch { res.writeHead(404,securityHeaders);res.end('Não encontrado'); } }
const server=http.createServer(async (req,res)=>{ const url=new URL(req.url,`http://${req.headers.host}`); try { if(url.pathname.startsWith('/api/') || url.pathname==='/health') await api(req,res,url); else await staticFile(req,res,url); } catch(e) { console.error(e); if(!res.headersSent) send(res,500,{error:'Erro interno.'}); } });
server.listen(PORT,HOST,()=>console.log(`CompraControl em http://${HOST}:${PORT}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>{db.close();process.exit(0)}));
