-- Execute este arquivo uma única vez no SQL Editor do seu projeto Supabase.
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('Administrador','Comprador','Consulta')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists sessions (
  token_hash text primary key,
  user_id bigint not null references users(id) on delete cascade,
  expires_at bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists suppliers (id bigint generated by default as identity primary key,name text not null,cnpj text,contact text,phone text,email text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists companies (id bigint generated by default as identity primary key,code text not null unique,name text not null,cnpj text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists categories (id bigint generated by default as identity primary key,name text not null unique,description text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists plans (id bigint generated by default as identity primary key,code text not null unique,name text not null,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists products (id bigint generated by default as identity primary key,name text not null,code text,category text,unit text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists invoices (id bigint generated by default as identity primary key,number text not null,date date not null,supplier text not null,sector text not null,plan_code text not null default '',total numeric not null check(total>=0),purchase_location text not null default '',company text not null default '',expense_type text not null default '',product_name text not null default '',quantity numeric not null default 0,created_at timestamptz not null default now());
create index if not exists products_name_idx on products (lower(name));
create index if not exists products_code_idx on products (lower(code));
create index if not exists sessions_expiry_idx on sessions (expires_at);

-- A chave secreta usada pela Vercel ignora RLS, portanto não exponha essa chave no front-end.
alter table users enable row level security;
alter table sessions enable row level security;
alter table suppliers enable row level security;
alter table companies enable row level security;
alter table categories enable row level security;
alter table plans enable row level security;
alter table products enable row level security;
alter table invoices enable row level security;
